CarterasFiammaWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CarterasFiammaWebApp.urls')),
    path('tienda/', include('TiendaOnline.urls')),
    path('carro/', include('carro.urls')),
    path('contacto/', include('contacto.urls')),
    path('autentificacion/', include('autentificacion.urls')),
]

TiendaOnline/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.tienda, name='Tienda'),
    ]

carro/urls.py
from django.urls import path
from . import views

app_name='carro'

urlpatterns = [
    path("agregar/<int:id>/", views.agregar_producto, name='agregar'),
    path("eliminar/<int:id>/", views.eliminar_producto, name='eliminar'),
    path('vaciar/', views.vaciar_carrito, name='vaciar')
    ]

TiendaOnline/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre=models.CharField(max_length=20)
    creacion=models.DateTimeField(auto_now_add=True)
    actualizacion=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=20)
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='mediaTienda', null=True, blank=True)
    precio=models.FloatField()
    descripcion=models.TextField()
    color=models.CharField(max_length=20)
    disponibilidad=models.BooleanField(default=True)
    creacion=models.DateTimeField(auto_now_add=True)
    actualizacion=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

TiendaOnline/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from .models import Producto #imoprtamos el models de prooducto para poder mostrarlos en el template de la tienda

# Create your views here.
def tienda(request):

    #para mostrar los productos creamos una lista donde almacenarlos
    productos=Producto.objects.all()

    return render(request, 'tienda/tienda.html', {'productos':productos})

TiendaOnline/templates/tienda/tienda.html
{%extends "base.html" %}

{%load static%}

{%block content %}
<!--
    las clases con las que estoy haciendo el css estan todas cargadas en el botstrap
-->
<div class="container">
    <div style="float:top; margin: 10px;">
        {% if request.user.is_authenticated %}
            {%include "carro/widget.html"%}
        {% else %}
            <div class="alert alert-danger"; style="text-align: center;" >Para realizar la compra debe registrarse</div> 
        {% endif %}
    </div>
    <div class="row">
{% for producto in productos %}
        <div class="col-md-4">
        <div class="card" style="width: 100%; margin: 10px 10px;">
            <img src="{{producto.imagen.url}}" class="card-img-top">
            <div class="card-body" style="text-align: center;">
                <h6 class="card-title">{{producto.nombre}}</h6>
                <p class="card-text">{{producto.descripcion}}</p>
                <p class="card-text">$&nbsp;{{producto.precio}}</p>
                            
            </div>
            <div class="card-footer text-center">
                <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-succes">Agregar al carrito</a>
            </div>
        </div>
        </div>

{%endfor%}
    </div>
</div>
{%endblock%}