CarterasFiammaWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CarterasFiammaWebApp.urls')),
    path('tienda/', include('TiendaOnline.urls')),
    path('carro/', include('carro.urls')),
    path('contacto/', include('contacto.urls')),
    path('autentificacion/', include('autentificacion.urls')),
]

TiendaOnline/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.tienda, name='Tienda'),
    ]

carro/urls.py
from django.urls import path
from . import views

app_name='carro'

urlpatterns = [
    path("agregar/<int:id>/", views.agregar_producto, name='agregar'),
    path("eliminar/<int:id>/", views.eliminar_producto, name='eliminar'),
    path('vaciar/', views.vaciar_carrito, name='vaciar')
    ]

TiendaOnline/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre=models.CharField(max_length=20)
    creacion=models.DateTimeField(auto_now_add=True)
    actualizacion=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=20)
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='mediaTienda', null=True, blank=True)
    precio=models.FloatField()
    descripcion=models.TextField()
    color=models.CharField(max_length=20)
    disponibilidad=models.BooleanField(default=True)
    creacion=models.DateTimeField(auto_now_add=True)
    actualizacion=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

carro/models.py
from django.db import models

# Create your models here.

TiendaOnline/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from .models import Producto #imoprtamos el models de prooducto para poder mostrarlos en el template de la tienda

# Create your views here.
def tienda(request):

    #para mostrar los productos creamos una lista donde almacenarlos
    productos=Producto.objects.all()

    return render(request, 'tienda/tienda.html', {'productos':productos})

carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from TiendaOnline.models import Producto

# Create your views here.

def agregar_producto(request,id):
    carro=Carro(request)
    producto=Producto.objects.get(id=id)
    carro.agregar_producto(producto=producto)
    return redirect('Tienda') #redireccionar a la tienda


def eliminar_producto(request,id):
    carro=Carro(request)
    producto=Producto.objects.get(id=id)
    carro.eliminar_producto(producto=producto)
    return redirect('Tienda') #redireccionar a la tienda


def vaciar_carrito(request):
    carro=Carro(request)
    carro.vaciar_carro()
    return redirect('Tienda')













TiendaOnline/templates/carro/widget.html
<table class="table table-bordered" style="color: rgb(255, 255, 255)">

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carrito de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Color</th>
            <th>Precio</th>
        </tr>
    </thead>

    <tbody>
        {%if request.session.carro.items %}
            {%for keys, value in request.session.carro.items%}
                <!--a cada bucle se agrega una fila con la compra-->
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.color}}</td>
                    <td>
                        {{value.precio}}
                        <a href="{% url 'carro:eliminar' value.id %}" class="btn btn-sm btn-succes">Eliminar</a>
                    </td>
                </tr>
            {%endfor%}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {%endif%}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                Subtotal : $ {{importe_total}}
                <a href="{% url 'Autentificacion' %}" class="btn btn-success" style= "float: right;">Hacer Pedido</a>
            </td>
            
        </tr>
    </tfoot>


</table>